### ISSUE TITLE
Project: User Definition

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#100]
## Problem statement

In regards to Auro and it's related assets, who are the different user types and their needs? Who are the different stakeholder groups and their needs? How do we use this insight to help clarify problems that need to solve and whether delivered solutions are solving them?

## Approach

In team discussion, we have personified two groups with three sub-groups each. 

- Engineers
  - Engineer: skepticism, "Why, just why?"
  - Engineer type: consumer, "What is Auro for me?"
  - Engineer type: contributor, "What can I do to help?"

- Designers 
  - Designer: skepticism, "Here we are again, is this real this time?"
  - Designer: consumer, "I love this, when can I get it?" 
  - Designer: consulting, "How does this solve my problem?"

The approach is to quantify these personas and have a clear definition for each to guide us with our content strategy. 

## Hypothesis 

Once the data is c collected that helps address the questions of user types and stakeholder groups, the assumption is that the Auro team can be extremely clear in their communication and have the utmost confidence that the deliverables from the team will meet their expectations.

**Comment by geoffrey1218** [comment]
Some thoughts on the engineer types:
- The skeptic — it seems like the skepticism is usually around the components. Most people I've worked with see the benefits of the tokens and WCSS, but initially balk at the components. I think this skepticism can come in a couple different flavors, depending on the question they're asking
    - Why can't I write my own HTML/CSS like I've always done? A button isn't that complicated.
    - Why aren't you just providing CSS files? You shouldn't need Javascript just to render a button.
    - We need components, but pretty much everyone is using React. Why aren't you just writing React components?
- The consumer — the most important thing for this group is keeping it simple to consume the design system. I think the demos definitely help with that.
    - There's a lot of concepts you need to somewhat understand to start using the components — custom elements, how to load polyfills, where to import the elements, shadow DOM & its implications, etc. I think making sure the docs are clear and accessible will help onboard people.
    - I also think it's important to have a go-to dev (Auro Champion?) in each product group who can help engineers as issues arise. Not everyone needs to know how to setup a project for consuming custom elements from scratch.
    - We also need to make it clear that the components cannot solve for every use-case right-off-the-bat. Everyone needs to be comfortable opening issues on GitHub if they're having problems. I've been doing my best to encourage that.

- The contributor — it feels like only a few devs will be at this point, at least until more people get to try out building components.
    - First step to this role is opening issues on GitHub.
    - There's a learning curve to building custom elements, especially depending on people's experience with front-end frameworks
    - I think having solid unit tests around the elements would make it easier for people to contribute, so we have assurance that there weren't any regressions.

**Comment by blackfalcon** [comment]
No resources to really dig into this as an independent epic.
