### ISSUE TITLE
Define Auro users

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#101]
# User story

As a product manager of the Auro Design System, I want to be able to clearly know who my users and stakeholders are, so I can clearly communicate and deliver value to these groups.

## Outline subtasks or tasks

The scope of this story is to define the approach that will be taken to establish the data needed to define who Auro's key users and stakeholders are. 

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

This story will be considered complete once the approach to the epic has been defined.

**Comment by ecommerceUXdesign** [comment]
Team meeting was successful. An initial definition of personas was discussed and the next step is to consult with Research as how to quantify this list.

**Comment by blackfalcon** [comment]
The scope of this issue is in limbo as we are requiring additional data to move forward. @blackfalcon is responsible for the next steps for validating these assumptions and communicating back to the team.

**Comment by blackfalcon** [comment]
No resources to really dig into this as an independent issue.
