### ISSUE TITLE
Tab button, tab strip, tabs

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#13]
## What is the requested web component?

Tabs organize content across different screens, data sets, and other interactions.

## Features

1. Allow for aggregation of content in a confined space
1. Allow for any configuration of tab-style data

## Is there any prior art related to this proposal?

- [x] YES
- [ ] NO

### Prior art

<img width="981" alt="Screen Shot 2020-03-05 at 3 51 56 PM" src="https://user-images.githubusercontent.com/181089/76036547-44102d80-5ef9-11ea-8458-43d85a63397a.png">
<img width="1042" alt="Screen Shot 2020-03-05 at 4 13 02 PM" src="https://user-images.githubusercontent.com/181089/76037567-3e681700-5efc-11ea-9eca-26812087d062.png">

## Agreement

By checking the box below I acknowledge that the proposed web component does not duplicate any existing feature or functionality within the Auro Design System. The proposal is requesting support for a feature that is currently not supported.

- [x] I certify that this proposal does not replicate any existing design or functionality.

## Additional context

Children stories: 

1. https://github.com/AlaskaAirlines/ods-hyperlink/issues/25
1. https://github.com/AlaskaAirlines/ods-hyperlink/issues/26

**Comment by erikalanghauser** [comment]
Tabs used on Change Reservation page:
![Web_keepchangecancel](https://user-images.githubusercontent.com/34354487/77575802-51359200-6e91-11ea-9ecb-6912d53eca53.png)
![Mobile_keepchangecancel](https://user-images.githubusercontent.com/34354487/77575805-51ce2880-6e91-11ea-8897-7ecab25bf644.png)

https://share.goabstract.com/98d91f82-f243-4862-8fd0-7919fa039bfd
