### ISSUE TITLE
Day/Date Picker

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#133]
# Component Audit

The scope of this issue is to track the full progress of the Day/Date Picker component.

## Process

This issue is to remain open until all areas of the specification and all assets have been delivered to stakeholders and user groups.

As new issues are created that are children of this Audit item, please be sure to reference this Audit item in that issue.

As assets are delivered, it is required that the labels associated with this Audit issue are updated to reflect status. Labels are as follows:

- Artwork
- Code
- Docs
- Ui Kit

This Audit issue will remain open until all assets have been delivered be it V0 or ADS compliment.

**Comment by blackfalcon** [comment]
Spec to consider. A date picker has some real a11y issues. Also, just because it is accessible, is it usable. I propose that a fly-out calendar is at minimum accessible via tabbing through. But in regards to visual impairments, the fly-out calendar is aria-hidden. 

I propose that with each instance of a fly-out calendar, it must be coupled with a text input that has a date structure to it that makes it very easy for date entry and is very accessible for visually impaired users. 

See https://github.com/AlaskaAirlines/auro/issues/183

**Comment by littleninja** [comment]
It's feasible that a datepicker offer both graphical and text input affordances for picking dates. Airbnb's react-date component was one source of inspiration: https://airbnb.io/react-dates (use Chrome).

What's the scope of this iteration? Any UX/UI designs for it yet?
