### ISSUE TITLE
auro-modal; new design review

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#168]
# User story

As a UI designer of Auro, I want to be able to review the work, so I can give feedback and prepare for next steps.

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [x] review work as presented by the product designer
- [x] provide feedback
- [x] prepare for next steps of development and symbolize

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

This story will be considered done when the presented work has been approved and prepared for dev work and symbolization.

### reference

https://github.com/AlaskaAirlines/auro/issues/11

**Comment by blackfalcon** [comment]
@vidalmenAS is there an ETA on when this blocked issue may be resolved?

**Comment by Crea-Ive** [comment]
@vidalmenAS  and I reviewed the basic structure of the modal and motion design. I'm currently working on the UX guidelines for the component.
