### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#19]
## What is the requested web component?

A breadcrumb can contain a divider to show the relationship between sections, this can be formatted as an icon or text.

## Features

TBD

1. ...
1. ...
1. ...
1. ...

## Is there any prior art related to this proposal?

- [x] YES
- [ ] NO

### Prior art

<img width="756" alt="Screen Shot 2020-03-06 at 10 24 45 AM" src="https://user-images.githubusercontent.com/181089/76111233-c568ce00-5f94-11ea-927f-22e832a5fbf6.png">

## Agreement

By checking the box below I acknowledge that the proposed web component does not duplicate any existing feature or functionality within the Auro Design System. The proposal is requesting support for a feature that is currently not supported.

- [x] I certify that this proposal does not replicate any existing design or functionality.

## Additional context

TBD

**Comment by znewton** [comment]
I know there has been discussion in the Retain Content space around finding a system for Breadcrumbs. Given that we own the global HeaderFooter, it could make logical sense for us to own the system for maintaining a "breadcrumb history/context". Adding value to HeaderFooter as a global element is at the forefront of our Sustainment initiatives as a team right now.

**Comment by blackfalcon** [comment]
v0 Art/Code exists - needs systemization
