### ISSUE TITLE
auro-carousel; new symbolize

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#194]
# User story

As a designer, I want to be able to have access to a symbolized version, so I can easily reuse with my project.

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [ ] Add completed work to UI Kit as Sketch Symbol

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

- [x] the documented design spec has been created
- [x] assets have been symbolized in the UI toolkit
- [x] new UI has been applied to the WC

#### reference

https://github.com/AlaskaAirlines/auro/issues/192

**Comment by ecommerceUXdesign** [comment]
@sryckman Can you please update the status of this task in the design process?

**Comment by blackfalcon** [comment]
@vidalmenAS or @sryckman is there an update to this? If no one is able to address this work during sprint 22, I will set the status to BLOCKED and place work back into the BACKLOG to be addressed later.

**Comment by sryckman** [comment]
It's done, I'm not sure what to do with this next.

**Comment by blackfalcon** [comment]
If the work is done, closing the ticket was the thing to do.
