### ISSUE TITLE
auro-carousel; new development

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#195]
# User story

As a Developer, I want to be able to use a web component, so I can quickly develop my team's feature.

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [x] Address all design and UX as proposed in the design comp in relation to using Auro specifications
- [x] A11y in regards to role and live notifications need to be coded into the final WC
- [x] Review demo with the designer as well as the Auro team
- [x] All new work to be reviewed by Auro team

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

#### Has been tested in all browsers

- [x] Chrome
- [x] Firefox
- [x] Edge (79 +)
- [x] Safari
- [x] Mobile Safari
- [x] IE11

#### Has been tested for accessibility

- [x] Screenreader
- [x] Axe
- [x] Keyboard use

#### Performance

- [x] Chrome Lighthhouse report

#### Auro component features

- [x] README doc completed with all relative information
- [x] API documentation created
- [x] Bundled version tested and documented
- [x] Examples and use case info created
- [x] Pages added to the Auro Doc Site

## Audit

https://github.com/AlaskaAirlines/auro/issues/192

**Comment by geoffrich** [comment]
PR is out for development review: https://github.com/AlaskaAirlines/auro-carousel/pull/1

Demo has been reviewed with @sryckman and approved from a design perspective.

**Comment by geoffrich** [comment]
All tasks complete. v1 has been released and doc site has been updated.
