### ISSUE TITLE
auro-carousel; new design

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#196]
# User story

As a designer, I want a standard UI and symbol for this component, so I can easily replicate in my designs.

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [ ] Assigned designer to consult with Product and Sr. UI Designer for UI specs
- [ ] Assigned designer to complete the design process as dictated by the framework
- [ ] Assigned designer to address steps as outlined below and assist in the development handoff process

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

- [x] Backlogged
- [x] Discovery
- [x] Design
- [x] [Review](https://github.com/AlaskaAirlines/auro/issues/193)
- [x] [Production](https://github.com/AlaskaAirlines/auro/issues/195)
- [x] [Symbolizing](https://github.com/AlaskaAirlines/auro/issues/194)
- [x] Complete

## Audit

https://github.com/AlaskaAirlines/auro/issues/192

**Comment by sryckman** [comment]
[Carousel for shoulder dates](https://share.goabstract.com/60c79297-cbf7-44bd-a791-febe4ac43b00)

**Comment by blackfalcon** [comment]
The design and review process need to be officially closed by @vidalmenAS and @sryckman for handoff to @geoffrich for development.

**Comment by sryckman** [comment]
Whoops was editing wrong ticket.

**Comment by blackfalcon** [comment]
Updated this ticket to reflect as what I see as reality. The REVIEW ticket is not closed and development has yet to be started.

**Comment by blackfalcon** [comment]
Waiting on the [symbolizing](https://github.com/AlaskaAirlines/auro/issues/194) task to be completed.

@sryckman or @vidalmenAS who is responsible for addressing this?
