### ISSUE TITLE
auro-pane; new design

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#202]
# User story

As a designer, I want a standard UI and symbol for this component, so I can easily replicate in my designs.

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [x] Assigned designer to consult with Product and Sr. UI Designer for UI specs
- [x] Assigned designer to complete the design process as dictated by the framework
- [x] Assigned designer to address steps as outlined below and assist in the development handoff process

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

- [x] Backlogged
- [x] Discovery
- [x] Design
- [x] [Review](https://github.com/AlaskaAirlines/auro/issues/203)
- [x] [Production](https://github.com/AlaskaAirlines/auro/issues/204)
- [ ] [Symbolizing](https://github.com/AlaskaAirlines/auro/issues/205)
- [ ] Complete

## Audit

https://github.com/AlaskaAirlines/auro/issues/201

**Comment by blackfalcon** [comment]
Design kickoff completed. Status is `in progress` until there is feedback from @sryckman.

**Comment by sryckman** [comment]
[Shoulder dates](https://share.goabstract.com/b1d7152a-14c8-4fa2-9dbc-f56ef347e361)

**Comment by blackfalcon** [comment]
Artwork is complete and review is in progress.

**Comment by blackfalcon** [comment]
Review complete, development ready to start.

**Comment by blackfalcon** [comment]
Reopened ticket as not all items related are complete. This ticket is to be closed when development has also been completed and all assets are symbolized and merged into UI Kit.

**Comment by sryckman** [comment]
@vidalmenAS Could you update symbol status? I think we are close to checking those two last checkmarks off, but I believe only a design system designer can move something from doc framework to the Auro Toolkit?

**Comment by blackfalcon** [comment]
@vidalmenAS or @sryckman is there an update to this? If no one is able to address this work during sprint 22, I will set the status to BLOCKED and place work back into the BACKLOG to be addressed later.

**Comment by sryckman** [comment]
It's done, I'm going to try "close with comment" and hope that's the right button.
