### ISSUE TITLE
auro-pane; new design review

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#203]
# User story

As a UI designer of Auro, I want to be able to review the work, so I can give feedback and prepare for next steps.

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [x] review work as presented by the product designer
- [x] provide feedback
- [ ] prepare for next steps of development and symbolize
- [ ] Add a link to Abstract in story comments

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

This story will be considered done when the presented work has been approved and prepared for dev work and symbolization.

### reference

https://github.com/AlaskaAirlines/auro/issues/201

**Comment by sryckman** [comment]
@vidalmenAS Moved into WIP/Ready for review! Please check the checkboxes.

[Abstract: Auro-pane (shoulder dates)](https://share.goabstract.com/b1d7152a-14c8-4fa2-9dbc-f56ef347e361)

**Comment by vidalmenAS** [comment]
@sryckman artwork approved @blackfalcon work is blocked and not considered complete component until all elements have been documented and symbolized. Only approved for suze's immediate usage. No other designer can use until this is documented and symbolized.

**Comment by ecommerceUXdesign** [comment]
Artwork: ADS compliant and Docs: Backlogged are labels to be used for the Parent Audit Story. Tickets in play only need to illustrate Epic they are associated with, type of work and that work's status. 

Note: Status: WIP and Status: Blocked should be used together.

**Comment by vidalmenAS** [comment]
@blackfalcon artwork and docs complete. I need to symbolize. https://share.goabstract.com/07d57907-2fef-4d20-97f6-6f3d93ec0e02

**Comment by sryckman** [comment]
There are already symbols! Check them out.

On Sep 4, 2020, at 12:58 PM, Vidal Men <notifications@github.com> wrote:

﻿
[EXTERNAL SENDER]


@blackfalcon<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fblackfalcon&data=02%7C01%7Csuzanne.ryckman%40alaskaair.com%7C620414fb98774f03657008d8510ce826%7C0f44c5d442b045c2bf55d0fea8430d33%7C0%7C1%7C637348463158165164&sdata=bwczUr26X8nUJoXrDpA4j72V2O0v8JAUVjNPKhuadhM%3D&reserved=0> artwork and docs complete. I need to symbolize. https://share.goabstract.com/07d57907-2fef-4d20-97f6-6f3d93ec0e02<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fshare.goabstract.com%2F07d57907-2fef-4d20-97f6-6f3d93ec0e02&data=02%7C01%7Csuzanne.ryckman%40alaskaair.com%7C620414fb98774f03657008d8510ce826%7C0f44c5d442b045c2bf55d0fea8430d33%7C0%7C1%7C637348463158175155&sdata=5sNPQQWgID3RdrKa3OLOmxNBYUGNcj64f%2Fx6a%2BZWluU%3D&reserved=0>
