### ISSUE TITLE
auro-pane; new design symbolize

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#205]
# User story

As a designer, I want to be able to have access to a symbolized version, so I can easily reuse with my project.

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [ ] Add completed work to UI Kit as Sketch Symbol

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

- [x] the documented design spec has been created
- [x] assets have been symbolized in the UI toolkit
- [x] new UI has been applied to the WC

#### reference

https://github.com/AlaskaAirlines/auro/issues/201

**Comment by blackfalcon** [comment]
@sryckman and @vidalmenAS is this step complete?

**Comment by vidalmenAS** [comment]
@blackfalcon - @sryckman went above and beyond and symbolized! I'm refining my backlog today and this is on my list to merge into our sketch library. leaving this open until i do this.
