### ISSUE TITLE
Back to Top

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#227]
# Component Audit

The scope of this issue is to track the full progress of the auro-back-to-top component.

## Process

This issue is to remain open until all areas of the specification and all assets have been delivered to stakeholders and user groups.

As new issues are created that are children of this Audit item, please be sure to reference this Audit item in that issue.

As assets are delivered, it is required that the labels associated with this Audit issue are updated to reflect status. Labels are as follows:

- Artwork
- Code
- Docs
- Ui Kit

This Audit issue will remain open until all assets have been delivered be it V0 or ADS compliment.

**Comment by blackfalcon** [comment]
New custom element is currently under development within AuroLabs.

**Comment by littleninja** [comment]
@blackfalcon code has been peer-reviewed and prerelease version will go live in the oneworld Hub page. Are we awaiting design artifacts at this point?

**Comment by blackfalcon** [comment]
@littleninja more information about how to transition from AuroLabs to Auro Design System is coming soon.

**Comment by blackfalcon** [comment]
v1.0 @aurolabs npm has been released.
