### ISSUE TITLE
auro-button: NotSupportedError: A newly constructed custom element must not have attributes

### ISSUE THREAD

**Issue by whexberg** [AlaskaAirlines/auro#239]
## Describe the bug
Our react (v17.0.2) application is having trouble rendering in Safari, whenever we use an auro-button. In chrome, and edge, everything seems to be fine.

## To Reproduce
1. import "@alaskaairux/auro-button";
2. Attempt to render an <auro-button> inside of any component
3. Start and then visit the application in your browser

## Expected behavior
Application should render

## Screenshots
<img width="1043" alt="Screen Shot 2021-06-07 at 2 08 12 PM" src="https://user-images.githubusercontent.com/12180119/121087876-d016a200-c799-11eb-967c-05c2ece84d5c.png">
<img width="553" alt="Screen Shot 2021-06-07 at 2 20 42 PM" src="https://user-images.githubusercontent.com/12180119/121089638-503e0700-c79c-11eb-8224-a17fb74c4d02.png">

## Desktop (please complete the following information):
 - OS: MacOS Big Sur 11.4 (20F71)
 - Browser: Safari
 - Version: 14.1.1 (16611.2.7.1.4)
 - React Version: v17.0.2

## Smartphone (please complete the following information):
 - Have not tried, yet

## Additional context
So far, this seems to be happening on 3 different machines using Safari. Also, when running playwright tests with jest, in headless mode, we get similar rendering errors.

After days of tinkering, we've made some progress, but we're not sure of the consequences. If I go to `node_modules/@alaskaairux/auro-button/dist/auro-button.js`, on line 39 there is a polyfill applied to the shadow root. Commenting out this line seems to fix the issue, however, I'm not familiar with this particular function and do not know the consequences of removing it.

**Comment by blackfalcon** [comment]
Thanks for this issue. I feel that this issue is related to a past issue that was resolved. https://github.com/AlaskaAirlines/auro-button/issues/112

What version of the auro-button are you using? This issue was just recently updated.

**Comment by blackfalcon** [comment]
This link https://auro.alaskaair.com/components/auro/button is the latest version of the component and this is a React app. Do you see the issue here as well?

**Comment by whexberg** [comment]
> Thanks for this issue. I feel that this issue is related to a past issue that was resolved. [AlaskaAirlines/auro-button#112](https://github.com/AlaskaAirlines/auro-button/issues/112)
> 
> What version of the auro-button are you using? This issue was just recently updated.

You're absolutely right! I updated to the latest version, and all seems well, now. Thank you!
