### ISSUE TITLE
Clean up npm packages.

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro#248]
There are a lot of packages out there from legacy namespaces and outdated versions. https://www.npmjs.com/settings/alaskaairux/packages

These need to be fully deprecated to alert consumers about unsupported versions and where to get new versions. 

#### Note
Add an issue for this per repo during refinement

**Comment by blackfalcon** [comment]
A current list of released npm packages

| Name | @aurodesignsystem | @alaskaairux | Legacy version deprecated | Notes|
|---|---|---|---|---|
| Icons | | √ | | No current issue to update
| WCSS | | √ | | No current issue to update 
| Checkbox | | √ | | https://github.com/AlaskaAirlines/auro-checkbox/issues/6
| Design Tokens | | √ | | No current issue to update
| table | | √ | | https://github.com/AlaskaAirlines/auro-table/issues/14
| radio | | √ | | https://github.com/AlaskaAirlines/auro-radio/issues/52
| hyperlink | | √ | | https://github.com/AlaskaAirlines/auro-hyperlink/issues/73
| loader | | √ | | https://github.com/AlaskaAirlines/auro-loader/issues/4
| badge | | √ | | https://github.com/AlaskaAirlines/auro-badge/issues/7
| icon | | √ | | https://github.com/AlaskaAirlines/auro-icon/issues/16
| interruption | | √ | | https://github.com/AlaskaAirlines/auro-interruption/issues/27
| accordion | | √ | | https://github.com/AlaskaAirlines/auro-accordion/issues/11
| header | | √ | | https://github.com/AlaskaAirlines/auro-header/issues/13
| card | | √ | | next version is still TBD... 
| popover | | √ | | https://github.com/AlaskaAirlines/auro-popover/issues/22
| flight | | √ | |  no plans at this time
| flightline | | √ | |  no plans at this time
| button | | √ | |  https://github.com/AlaskaAirlines/auro-button/issues/106
| carousel | | √ | |  https://github.com/AlaskaAirlines/auro-carousel/issues/6
| pane | | √ | |  https://github.com/AlaskaAirlines/auro-pane/issues/7
| datetime | | √ | |  https://github.com/AlaskaAirlines/auro-datetime/issues/6
| eslint-config | √ |  | no legacy version |
| wc-generator | √ |  | √ |
| lockup | √ |  | √ | 
| alert | √ |  | √ |
| skeleton | √ |  | √ |
| background | √ |  | √ |  
| avatar | √ |  | √ |
| input | √ |  | √ |
| tokenlist | √ |  | √ |

**Comment by blackfalcon** [comment]
This issue is not being maintained to track the namespace transfer.
