### ISSUE TITLE
NEW ELEMENT: YouTube (Accessible Videos)  

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro#260]
Example: https://www.alaskaair.com/content/explore/ski/alyeska  Video's on as.com must have captions to be accessible.  

If we don't have captions we use this component to send people to YouTube to watch the video.

**Comment by blackfalcon** [comment]
The formula for retrieving the large thumbnail of the video. 

```html
https://img.youtube.com/vi/<insert-youtube-video-id-here>/maxresdefault.jpg
```

**Comment by blackfalcon** [comment]
I see that the Content Enablement team is looking at building a youtube element. Looking to understand the scope of that work and determine if it's appropriate for that element to be in the design system or Airframe?
