### ISSUE TITLE
Figma design token components

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro#264]
# General Support Request
Help designers and engineerings have a clear understanding of what colors are being used in a design.

## Possible Solution
Create a component label that already contains design token names. These will be matched to the Figma style names. Release to designers.

Will be posted here: https://www.figma.com/file/VpUz89Ov6ImBpY5YvzYbZW/Auro-toolkit?node-id=1223%3A2070

**Comment by leeejune** [comment]
Released on Figma and Teams channel. @blackfalcon How should we add it to the doc site?

**Comment by blackfalcon** [comment]
@leeejune isn't that what we have here? https://auro.alaskaair.com/getting-started/developers/design-tokens

**Comment by leeejune** [comment]
@blackfalcon I meant adding the new colors? I can't seem to find the update on the current doc site.

**Comment by blackfalcon** [comment]
This issue has been resolved. Tokens now appear in the Auro doc site.
