### ISSUE TITLE
auro-breadcrumbs Blueprint

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro#270]
# Blueprint
We need a blueprint for a breadcrumb component that matches the features we want to have.

## Outline tasks

- [ ] anatomy
- [ ] color
- [ ] typography
- [ ] layout
- [ ] spacing
- [ ] animation/behavior
- [ ] variants
- [ ] states (hover, focus, active, focus-visible)
- [ ] a11y

## Optional

- [ ] Competitive analysis
- [ ] research
- [ ] site audit
- [ ] usage audit
- [ ] inspirational work

**Comment by leeejune** [comment]
**Progress update:**

**Week 1 (9/13-9/20): Research**

- psychology - why we need this component
- competitive research
- best practices
- definition/use cases
- why choose this component?
- relationship with other components
- mega menu vs secondary nav explorations

**Week 2 (9/20-9/27): Define & Proposal**

- have definitions filled out
- apply new definitions/rules to existing product
- propose new solutions

**Week 3-4 (9/27-10/11): Testing & Refining**

- Finish up definitions from Week 2
- 3 proposal examples to test new definitions on (apply navigation components to existing pages)
- Pressure test components against defintions

**Week 5-6 (10/18-11/1): Design Iteration**

- Choose 1 “failing” page/flow and use our new nav components to turn it into a “passing” flow
- Evaluate which nav components are best for each flow
- Finalize or iterate on UI

**Week 7-8 (11/1-11/14): Feedback & Responsive Design**

- Figure out UI for desktop, tablet, and mobile designs
- Get feedback from other product/UI designers from design fair & UI sync
- Pick a page and design for all screen sizes

**Comment by leeejune** [comment]
[Link to completed blueprint](https://www.figma.com/file/OJoHbhCPRr8P6DEAvSZyL4/Breadcrumb?node-id=322%3A298&t=CyjPkyEcQQJU5x4K-1)

**Comment by leeejune** [comment]
@jordanjones243 Here's the mobile blueprint: https://www.figma.com/file/OJoHbhCPRr8P6DEAvSZyL4/Breadcrumb?node-id=1724%3A1545&t=yg66a1d8Rjty0FL0-1
