### ISSUE TITLE
Create New power point template

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro#278]
# User story

As a Alaska employee I want a power point template so that I can quickly create new slides that are visually appealing and consistent.

## Definition of “Done” (exit criteria)
- [ ] A roadmap template slide is created
- [ ] A team intro template slide is created
- [ ] A title slide (new section, transition between sections)
- [ ] A text content slide
- [ ] A slide with a circle picture on the right that automatically crops the picture and text on the left.
- [ ] The slide template is made available somewhere on the auro doc site.

**Comment by blackfalcon** [comment]
@leeejune you are pretty overloaded. @jdeeezzy is this something you may be interested in?
