### ISSUE TITLE
Symbolize: alerts

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#90]
# User story

As a designer, I want to be able to have access to the approved symbol, so I can complete design specs for my team.

## Outline subtasks or tasks

Extension of: https://github.com/AlaskaAirlines/auro_docs/issues/83
Child of: https://github.com/AlaskaAirlines/auro_docs/issues/17

> List specific steps required to deliver this work.

- [ ] Document approved art in UIKit
- [ ] Symbolize
- [ ] Communicate

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

- [ ] the documented design spec has been created
- [ ] assets have been symbolized in the UI toolkit
- [ ] new UI has been applied to the WC

**Comment by ecommerceUXdesign** [comment]
Web component feature has been released. @vidalmenAS and @erikalanghauser can you please update as to the status of design documentation?

**Comment by erikalanghauser** [comment]
Has not gone through full Auro documentation framework. However, artwork for V0 is available in Abstract https://share.goabstract.com/ba4c13a1-9f90-4dcb-b720-9d00e83b093d.

**Comment by blackfalcon** [comment]
> Has not gone through full Auro documentation framework. However, artwork for V0 is available in Abstract https://share.goabstract.com/ba4c13a1-9f90-4dcb-b720-9d00e83b093d.

@vidalmenAS is this good to call complete then?
