### ISSUE TITLE
Breakup up IU KIt monolith 1/2

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#92]
# User story

As a designer, I want to be able to consume individual UI libraries, so I can easily maintain my design resources.

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [x] Identify individual components within the UI Kit monolith 
- [ ] consult with the team as to strategy for breaking up the UI Kit
- [ ] create the first library of resources 
- [ ] or create families of resources if optimal 
- [ ] catalog resources accordingly 
- [ ] identify next step in the process 

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

This story will be considered complete once the UI KIt has an agreed-upon strategy for breaking up the larger single resource into smaller independent resources. 

The scope of this story is NOT to break all the things up at once. The deliverable here is to identify a strategy moving forward and create the first individual library. 

All the work related to this story will be addressed in a new branch until ready for release. 

## Epic

https://github.com/AlaskaAirlines/auro_docs/issues/98

**Comment by vidalmenAS** [comment]
no updates this sprint / sidelined w ADS designer onboarding, oneworld and product design adhoc support.

**Comment by blackfalcon** [comment]
Unassigned, looking for help

**Comment by ecommerceUXdesign** [comment]
Suzanne Ryckman has already started a process for migrating all the Auro UI Kit files from Sketch to Figma. The scope of this 1st story has been addressed in that process.

**Comment by sryckman** [comment]
As I did this work individually during the Figma trial period, it would be good to have some discussions post Figma onboarding regarding how we want to continue to break out the libraries, as well as how to handle documentation for work in progress, updates, and additional resource files (for example, brand resources that aren't officially part of Auro, but worth keeping handy in Figma libraries for designers).
