### ISSUE TITLE
UI Kit, breaking apart the monolith 2/2

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#93]
# User story

As a designer, I want to be able to consume individual UI libraries, so I can easily maintain my design resources.

## Outline subtasks or tasks

All work per this issue is dependent on the deliver of https://github.com/AlaskaAirlines/auro_docs/issues/92

> List specific steps required to deliver this work.

- [ ] Based on work in https://github.com/AlaskaAirlines/auro_docs/issues/92, move onto the next component
- [ ] based on work at this point, determine if additional stories are needed

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

This story will be considered complete once the prerequisite of https://github.com/AlaskaAirlines/auro_docs/issues/92 is addressed, a next component and library was addressed and a plan to complete the work has been discussed and documented. 

## Epic

https://github.com/AlaskaAirlines/auro_docs/issues/98

**Comment by blackfalcon** [comment]
Unassigned, looking for help

**Comment by ecommerceUXdesign** [comment]
Assigned to Suzanne Ryckman. She is managing the process of migrating the Sketch UI Kit to Figma.

**Comment by sryckman** [comment]
Status: Working on file cleanup on and off throughout the week. I will set up a meeting later this week or next week to go over how we break out the sections.

**Comment by blackfalcon** [comment]
This work is still in progress and has created new work channels outside the scope of Auro.

**Comment by blackfalcon** [comment]
This work is continuous. But closing this specific issue.
